[project]
name = "stardist-hybrid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "csbdeep",
    "instanseg-torch",
    "keras",
    "numba",
    "numpy",
    "onnx",
    "onnxruntime",
    "opencv-python",
    "polars",
    "pydantic",
    "scikit-image",
    "tensorflow",
    "tf2onnx",
    "tifffile",
]

[tool.uv.extra-build-dependencies]
stardist-hybrid = ["numpy"]
